name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run_tests:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout acados
      uses: actions/checkout@v4
      with:
        repository: 'acados/acados'
        path: ${{github.workspace}}/acados
        fetch-depth: 2

    - name: Checkout seal
      uses: actions/checkout@v4
      with:
        path: ${{github.workspace}}/seal

    - name: Download acados artifacts (build, lib, include) into acados repository
      uses: actions/download-artifact@v4
      with:
        path: ${{github.workspace}}/acados
        repository: acados/acados
        github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
        run-id: 11513005717  # latest release build

    - name: Export Paths
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        echo "ACADOS_SOURCE_DIR=${{github.workspace}}/acados" >> $GITHUB_ENV
        echo "ACADOS_INSTALL_DIR=${{github.workspace}}/acados" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${{github.workspace}}/acados/lib" >> $GITHUB_ENV

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python interface
      working-directory: ${{github.workspace}}/acados
      run: |
        pip install --upgrade pip
        pip install interfaces/acados_template

    - name: Install Tera
      working-directory: ${{github.workspace}}/acados
      shell: bash
      run: ${{github.workspace}}/acados/.github/linux/install_tera.sh

    - name: Install seal
      working-directory: ${{github.workspace}}/seal
      run: |
        pip install -e .[test] 
        pip install torch --extra-index-url https://download.pytorch.org/whl/cpu

    - name: Run seal tests
      working-directory: ${{github.workspace}}/seal
      run: |
        pytest 
